### ISSUE TITLE
Need `select_paramval` function

### ISSUE THREAD

**Issue by maowerner** [martin-ueding/paramvalf#11]
In the rho analysis we obtain energy levels from plateau fits with certain parameters (matrixfit_model, tmin_offset, tmax_offset, ...) In the Breit-Wigner fit we use all thereby obtained points in a common fit. The parameters (in my case matrixfit_model) are however still present and cause the code to perform to seperate fits on points with the shifted and pc model. 

I would like to have a function which allows me to drop parameters (on my own risk) to combine data from different methods more easily. 
The hotfix I am using now is abusing `filter_paramval`
```
filter_paramval(fits, matrixfit_model %in% c('shifted', 'pc'))
```

**Comment by martin-ueding** [comment]
Add your parameters to the `convert` character vector [here](https://github.com/kostrzewa/LuescherAnalysis/blob/01bbba313a99fec2bef586f9c0131321082eed99/paramval/rho/breit_wigner_fit_data.R#L104). Then they get converted into values, do not participate in the group-by and are just discarded.

**Comment by martin-ueding** [comment]
If you just wanted to delete a parameter `deleteme` from an object `pv` you could also just do `pv$param$deleteme <- NULL` and it will be gone.
