### ISSUE TITLE
`df_to_paramval` should not be able to create duplicate parameter sets

### ISSUE THREAD

**Issue by maowerner** [martin-ueding/paramvalf#12]
I stumbled upon this be having a typo an creating a parameter set twice. This got carried through the whole analysis and in the plots behaved like an unresolved parameter. 

In my opinion there should be either an error or duplicate rows should be removed.

**Comment by martin-ueding** [comment]
So what did you do? Like this?

```r
df_to_paramval(df, c('foo', 'bar', 'foo'))
```

**Comment by martin-ueding** [comment]
Ah, you have created something like

```r
param = data.frame(foo = (1, 2, 1))
```

Yes, I can make than an error. Silently dropping them would not be my preference as it is a mistake in the data and should be fixed at the source.

**Comment by martin-ueding** [comment]
`pv_call` will now ~~raise~~ ~~throw~~ stop when you have non-unique rows in any of the `param` sections of the `pv` containers that you pass to it. This does not stop you from producing such containers, but it prevents you from using them.

This change ships in Release 2.4.0, which I already made `LuescherAnalysis` depend on such that you get a nagging to update.
