### ISSUE TITLE
tsv_to_paramval should also enter dependency structure

### ISSUE THREAD

**Issue by kostrzewa** [martin-ueding/paramvalf#18]
that way data files, if they change, cause the dependency tree to be regenerated

**Comment by martin-ueding** [comment]
The way that I have implemented these dependencies is by just having a specially crafted comment somewhere in the file, like this:

```r
# Depend: data/rho/bootstrap_parameters.tsv
bootstrap_parameters <- tsv_to_param('data/rho/bootstrap_parameters.tsv')
```

It also supports globs that are resolved during dependency scanning (before every call to `make`).

This way one can use any function and I do not have to properly parse all the R code.
