### ISSUE TITLE
```serial``` argument for pvcall missing in head commit of master branch

### ISSUE THREAD

**Issue by kostrzewa** [martin-ueding/paramvalf#2]
this makes it incompatible with the sigma analysis

**Comment by martin-ueding** [comment]
Sorry about that, the changes are now pushed.

**Comment by kostrzewa** [comment]
No worries, just wanted to point it out. I've simply omitted the argument in the calls in the various ```.Rmd``` files.

**Comment by martin-ueding** [comment]
The problem seems to be that the plotting functions do not produce output when they are called via an mclapply. Therefore you need this option in the documents in order to produce the full output.

**Comment by kostrzewa** [comment]
Yeah, I simply ran in debug mode.
