### ISSUE TITLE
handling of "Depend" not quite complete

### ISSUE THREAD

**Issue by kostrzewa** [martin-ueding/paramvalf#22]
It appears that the handling of "Depend" in ```paramval/cluster/{}.R``` files is not quite complete

It seems to work for some cases while failing for others. I haven't been able to fully understand why.

Adding more instances of ```f['depends']``` to ```scan-dependencies.py``` to the dictionary used for the rendering of the Makefile seems to help, but it does not fully solve the problem.

**Comment by kostrzewa** [comment]
My particular use-case is that I add explicit dependencies on files from the ```R/``` subdirectory via ```Depend:```.  This is in order to make sure that things are rerun if the relevant utility functions change.

Unfortunately, it seems like these dependencies are only picked up part of the time and I can't figure out why.

**Comment by martin-ueding** [comment]
I also have the feeling that it is a bit dodgy.

Independent of that I thought that it might makes sense to scan the R files for function definitions with `^([\w\d_.]+) <-` and then pattern match these in the files in the `paramval` directory to automatically deduce dependencies on R files. What do you think of that? The only issue would be a false-positive rate.

**Comment by martin-ueding** [comment]
Okay, that was not too hard to implement. But the rho flow diagram now has this monster in it:

![Bildschirmfoto_001](https://user-images.githubusercontent.com/976924/66846477-2e15c680-ef72-11e9-9637-b6b3ee8b704c.png)

I'll try moving that into paramvalf proper, perhaps that is already sufficient.

**Comment by martin-ueding** [comment]
Also I needed to exclude `RcppExports.R`. The rendering of the graph now takes a bit longer, but it seems that it works like you'd want. Also the functions show up in the `Makefile`.

**Comment by martin-ueding** [comment]
I am not sure whether in your case it does not pick up the `# Depend:` line or whether the files cannot be found. It uses globbing like this:

```r
    depends = [os.path.normpath(elem)
               for g in pattern_depend.findall(contents)
               for elem in glob.glob(g)]
```

So it searches for all occurrences of the pattern `^# Depend: (.*)$` and then puts what it finds in the capture group into the globbing. So if either fails, the dependency does not go through. As a side effect the `glob` function will silently drop paths that do not exist. That's not good here I realize. Let's make that an error.

**Comment by kostrzewa** [comment]
> I am not sure whether in your case it does not pick u

I think it did not pick up the depend for some reason, the file did definitely exist. I like the solution a lot! Even the "monster" is what it is. When that kind of thing develops, perhaps it's time to move it to paramvalf proper :)

**Comment by kostrzewa** [comment]
Thanks @martin-ueding
