### ISSUE TITLE
dplyr dependency and %>%

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/paramvalf#3]
The usage of the `%>%` operator from `dplyr` will fail in client code. The client currently needs to do `library(dplyr)` in order for this library to work. That does not make much sense.

Just including the `library(dplyr)` in `R/call.R` alone did not make any difference. Therefore it seems that one has to always load `dplyr` when loading this library.

**Comment by kostrzewa** [comment]
So, this can be fixed by using

```
dplyr::`%>%`
```

instead of ```%>%``` directly.

**Comment by kostrzewa** [comment]
Note that the ```library(dplyr)``` in ```R/call.R``` will be ignored in actual usage anyway. Only the function definitions are exported when the package is installed.

**Comment by kostrzewa** [comment]
You could solve the issue by doing it at the top of every function call instead, or you use the dplyr namespace.

**Comment by martin-ueding** [comment]
I prefer

    dplyr::`%>%`

**Comment by martin-ueding** [comment]
That unfortunately gives parsing errors. I just loaded the library int the function then.

**Comment by kostrzewa** [comment]
which parsing errors? I tried it out...

**Comment by martin-ueding** [comment]
I have tried the following:

```r
… pv$param dplyr::%>% group_by_at() …
… pv$param dplyr::`%>%` group_by_at() …
… pv$param `dplyr::%>%` group_by_at() …
```

And all of them give errors:

```
  /home/mu/Lattice/Code/paramvalf/R/call.R:104:25: unerwartetes Symbol
103: 
104:     grouped <- pv$param dplyr
                             ^
```

```
  /home/mu/Lattice/Code/paramvalf/R/call.R:104:25: unerwartetes Symbol
103: 
104:     grouped <- pv$param dplyr
                             ^
```

```
  /home/mu/Lattice/Code/paramvalf/R/call.R:104:25: unerwartetes Symbol
103: 
104:     grouped <- pv$param `dplyr::%>%`
                             ^
```

It seems to be impossible to use it as an infix operator with namespace qualification.

**Comment by martin-ueding** [comment]
You can do something like

    dplyr::`%>%`(df, func)

but that defeats the point of it being an infix operator.
