### ISSUE TITLE
Recovering row indices from filtering

### ISSUE THREAD

**Issue by kostrzewa** [martin-ueding/paramvalf#4]
After filtering a param data frame, it would be valuable to be able to recover the row indices of the rows that were filtered in the original, unfiltered data frame. This would then allow to select the values accordingly.

An approach which seems to work is the following:

```
require("dplyr")
load("rho_kinematics.Rdata")

boot_l_2_A30_32_param <- filter(rho_kinematics$param,
                                boot_l == 2,
                                ensemble == "A30.32")

matched <- unique(which( apply(X = rho_kinematics$param,
                               MARGIN = 1,
                               FUN = function(x){
                                 any(apply(X = boot_l_2_A30_32_param,
                                           MARGIN = 1,
                                           FUN = function(y){
                                             all(x == y,  
                                                 na.rm = TRUE)
                                           }
                                           )
                                     )
                               })
                       )
                   )                                                                                                                              

for( i in matched ){
  print(str(rho_kinematics$value[[i]]))
  readline()
}
```

**Comment by martin-ueding** [comment]
I think it would be easier to just let the framework create an additional column `id` or `idx` on all generated `param` data frames such that this filtering would work. This would now make a constructor necessary such that this is ensured even for user-supplied `param` data frames.

So just the following:

```r
paramval <- function (param, value) {
    pv <- list(param = param, value = value)
    pv$param$idx <- 1:nrow(pv$param)
    class(pv) <- append(class(pv), 'paramval')
    return (pv)
}
```

Then you can just do this:

```r
filtered <- dplyr::filter(pv$param, var == value)
pv$value[filtered$idx]
```

And every `pvcall` would ensure that this index column is correctly set up. Would that be what you need?

**Comment by martin-ueding** [comment]
And before joining two `paramval` objects one would have to remove these columns as they would spoil the join.

**Comment by kostrzewa** [comment]
> Then you can just do this:

I don't think so, value is a list.

**Comment by martin-ueding** [comment]
You can subset a list with an index vector when using `list.[`:

```
> list(1, 2, 3, 4)[2:3]
[[1]]
[1] 2

[[2]]
[1] 3
```

The `list.[` maps a list to a sublist. That is also why one has to use `list.[[` to extract a single element. So  `pv$value[index_vector]` works just fine.

**Comment by kostrzewa** [comment]
> You can subset a list with an index vector when using list.[:

Heh, this never worked for me, weird, cheers.

**Comment by martin-ueding** [comment]
There is now a new function which works like `dplyr::filter` on the `param` part and gives a new `paramval` object with the corresponding values. And using it is natural:

```r
filter_paramval(rho_outlier_keep, ensemble_base == 'A30')
```

Just pull with git, run in R `devtools::document(); install.packages(',', repo = NULL)` to get the latest version.

**Comment by kostrzewa** [comment]
Sounds great!
